### ISSUE TITLE
Update C++ Sheet

### ISSUE THREAD

**Issue by gibsjose** [gibsjose/cpp-cheat-sheet#1]
The data structures and algorithms sheet is pretty much filled out, but the C++ sheet is lacking...

**Comment by GetTurnedOn** [comment]
drank in java, such a cheat

**Comment by mo-messidi** [comment]
Great overview. Your find function in your map says m.find("value") returns "key". I think you you switch "key" and "value". I believe that the find() method in <map> takes a "key" not a "value".

**Comment by gibsjose** [comment]
@mo-messidi You're absolutely right. `std::map` does not include a method to search by value. You can use `find_if` with a comparison method, or Boost's Bimap.

I'll update to fix that. Thanks!

**Comment by jimaldon** [comment]
`std::multiset` is missing

**Comment by gibsjose** [comment]
@B1Z0N thanks for helping fill the C++ cheat sheet out!
