### ISSUE TITLE
Data structures and Algorithms Cheat sheet not updated

### ISSUE THREAD

**Issue by sanjanasekar** [gibsjose/cpp-cheat-sheet#13]
Knapsack and Travelling sales man algorithms missing in the data structures and algorithms cheat sheet

**Comment by gibsjose** [comment]
Unfortunately I don't have time to implement these anytime soon, but I would very much welcome a PR if someone wants to take a shot at it!

**Comment by finnthedawg** [comment]
The latest PR by B1Z0N seems to have added them.
