### ISSUE TITLE
Definition of min-heap and max-heap incorrect

### ISSUE THREAD

**Issue by indrajeet95** [gibsjose/cpp-cheat-sheet#15]
Under 1.10 Heap std:: priority queue
The definition of min-heap is provided as "A min-heap is structured with the root node as the smallest and each child subsequently smaller than its parent" which is incorrect because the root of tree would be the smallest element and its children would have a higher value than that. 
Similarly, the definition of max-heap also should be modified to "A max heap is structured with the root node as the largest and each child subsequently smaller than its parent".

**Comment by gibsjose** [comment]
Thanks! Fixed in c6836c2be11aca80d64571bb6339bab5d090f78f
